### ISSUE TITLE
Combine with io-array

### ISSUE THREAD

**Issue by zwhitchcox** [sunfishcode/io-streams#11]
Can you explain the rationale for combining the [`io-arrays`](https://github.com/sunfishcode/io-arrays) and `io-streams` crates? It seems like you could sometimes want to do both.

For instance, with the POSIX file descriptors you can `read`, `write`, and `lseek`. I think it would make more sense to provide both of these on the same "file descriptor" and just have a property like `is_seekable` for an `io-array`-like resource.

**Comment by zwhitchcox** [comment]
For a more concrete use case, consider sparse files. I may want to stream a file to a web server which does not support seeking, or I could be streaming to a file on my disk which does support seeking. It has the same functionality, but I'll just want to fill the sparse space with zeros.

**Comment by zwhitchcox** [comment]
I think this is a fundamental flaw in a lot of stream implementations. For instance Node streams and web streams have no concept of seek, even though they are frequently used in the use case above.

**Comment by sunfishcode** [comment]
One thing that might be worth considering for io-streams' API is a `write_zeros` function. That way, if the underlying device does support seeking, `write_zeros` could use it, and it could write explicit zeros otherwise. I think that would address the use case you describe.
