### ISSUE TITLE
Minimal implementation of unbuffered stdin and stdout

### ISSUE THREAD

**Issue by cole-miller** [sunfishcode/io-streams#9]
Hi! My current project wants unbuffered (locking is fine) access to stdin and stdout in certain cases, so I wrote [a tiny implementation](https://gist.github.com/cole-miller/8419bc0ae346a239a00df77a44b6d79b) based on the part of io-streams that does this. Did I capture the essential idea correctly? (Please feel free to close if this doesn't belong here in the issue tracker.)

**Comment by sunfishcode** [comment]
The one thing that stands out is that this code doesn't capture the Unicode handling on Windows. Otherwise, this looks like it should work, provided you don't need io-streams' other features.

**Comment by cole-miller** [comment]
> Unicode handling on Windows

Ugh, right—I should've caught that on my own. Thanks for the feedback and sorry for the noise here!
